
[package]
name = "gito_core"
version = "1.0.8"
description = "offering tiny easy-use api about git info"
categories = ["development-tools"]
readme = "./README.md"

[package.edition]
workspace = true

[package.authors]
workspace = true

[package.repository]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license]
workspace = true

[lib]
crate-type = ["cdylib","rlib"]

[dependencies]
regex = "1"
napi-derive = "2.12.2"

[dependencies.napi]
version = "2.12.0"
default-features = false
features = ["napi4"]

[build-dependencies]
napi-build = "2.0.1"

[features]
independent = ["napi-derive/noop"]
