[package]
name = "gito_core"
version = "1.0.2"
description = "offering tiny easy-use api about git info"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
readme.workspace = true
license.workspace = true
categories = ["development-tools"]


[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
regex = "1"


[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
