[package]
name = "gito"
version = "0.2.0"
description = "A tool to expand the ability of git"
categories = ["command-line-utilities"]
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
readme.workspace = true
license.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
regex = "1"
serde_json = "1.0.91"
colored = "2.0.0"
gito_core = "1.0.0"
rust-ini = "0.18.0"
dirs = "5.0.0"
home = "0.5.4"
prettytable = "0.10.0"
