[package]
name = "gito"
version = "0.2.7"
description = "A tool to expand the ability of git"
categories = ["command-line-utilities"]
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
readme.workspace = true
license.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
local_dep = {path = "../local_dep", version = "1.0.3"}
